export enum ChannelType {
    GUILD_TEXT = 0,
    DM,
    GUILD_VOICE,
    GROUP_DM,
    GUILD_CATEGORY,
    GUILD_NEWS,
    GUILD_STORE,
    GUILD_NEWS_THREAD,
    GUILD_PUBLIC,
    THREAD,
    GUILD_PRIVATE_THREAD,
    GUILD_STAGE_VOICE,
  }